# Copyright 2025 Sudo Sweden AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: "3.0.0"
info:
  version: 0.1.0
  title: dockyards-types
  description: no
components:
  schemas:
    options:
      properties:
        version:
          type: array
          items:
            type: string
        storage_resource_types:
          type: array
          items:
            type: string
      required:
      - version
    organization:
      properties:
        id:
          type: string
        name:
          type: string
        display_name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        duration:
          type: string
        deleted_at:
          type: string
          format: date-time
        condition:
          type: string
        voucher_code:
          type: string
        provider_id:
          type: string
        expires_at:
          type: string
          format: date-time
        credential_reference_name:
          type: string
      required:
      - id
      - name
      - created_at
    tokens:
      properties:
        AccessToken:
          type: string
        RefreshToken:
          type: string
      required:
      - AccessToken
      - RefreshToken
    login_options:
      properties:
        email:
          type: string
        password:
          type: string
      required:
      - email
      - password
    node_pool:
      properties:
        id:
          type: string
        cluster_id:
          type: string
        name:
          type: string
        control_plane:
          type: boolean
        control_plane_components_only:
          type: boolean
        load_balancer:
          type: boolean
        quantity:
          type: integer
        cpu_count:
          type: integer
        ram_size:
          type: string
        disk_size:
          type: string
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/node'
        storage_resources:
          type: array
          items:
            $ref: '#/components/schemas/storage_resource'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
      required:
      - id
      - name
    node_pool_options:
      properties:
        name:
          type: string
        control_plane:
          type: boolean
        control_plane_components_only:
          type: boolean
        load_balancer:
          type: boolean
        quantity:
          type: integer
        cpu_count:
          type: integer
        ram_size:
          type: string
        disk_size:
          type: string
        storage_resources:
          type: array
          items:
            $ref: '#/components/schemas/storage_resource'
    cluster_options:
      properties:
        name:
          type: string
        version:
          type: string
        node_pool_options:
          type: array
          items:
            $ref: '#/components/schemas/node_pool_options'
        ingress_provider:
          type: string
        no_ingress_provider:
          type: boolean
        no_cluster_apps:
          type: boolean
        allocate_internal_ip:
          type: boolean
        cluster_template:
          type: string
        duration:
          type: string
      required:
      - name
    cluster:
      properties:
        id:
          type: string
        name:
          type: string
        organization:
          type: string
        nodes_count:
          type: integer
        state:
          type: string
        version:
          type: string
        created_at:
          type: string
          format: date-time
        allocate_internal_ip:
          type: boolean
        duration:
          type: string
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
        condition:
          type: string
        dns_zones:
          type: array
          items:
            type: string
        api_endpoint:
          type: string
        expires_at:
          type: string
          format: date-time
        node_pools_count:
          type: integer
      required:
      - id
      - name
      - created_at
    credential:
      properties:
        id:
          type: string
        name:
          type: string
        data:
          type: object
          additionalProperties:
            type: string
            format: byte
        credential_template_name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
      required:
      - id
      - name
    credential_options:
      properties:
        name:
          type: string
        credential_template_name:
          type: string
        data:
          type: object
          additionalProperties:
            type: string
            format: byte
    user:
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        password:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        display_name:
          type: string
        provider_id:
          type: string
      required:
      - id
      - name
      - email
    node:
      properties:
        id:
          type: string
        name:
          type: string
        condition:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
        provider_id:
          type: string
        system_info:
          type: object
          additionalProperties:
            type: string
      required:
      - id
      - name
      - created_at
    storage_resource:
      properties:
        name:
          type: string
        type:
          type: string
        quantity:
          type: string
      required:
      - name
      - quantity
    unprocessable_entity_errors:
      properties:
        errors:
          type: array
          items:
            type: string
      required:
      - errors
    workload:
      properties:
        id:
          type: string
        name:
          type: string
        workload_template_name:
          type: string
        input:
          type: object
        namespace:
          type: string
        provenience:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
        condition:
          type: string
        urls:
          type: array
          items:
            type: string
          x-go-name: URLs
      required:
      - id
      - name
      - created_at
    workload_options:
      properties:
        name:
          type: string
        workload_template_name:
          type: string
        input:
          type: object
        namespace:
          type: string
    ip_pool:
      properties:
        id:
          type: string
        name:
          type: string
        addresses:
          type: array
          items:
            type: string
    identity_provider:
      properties:
        id:
          type: string
        name:
          type: string
        display_name:
          type: string
      required:
      - id
      - name
    organization_options:
      properties:
        display_name:
          type: string
        duration:
          type: string
        voucher_code:
          type: string
        credential_reference_name:
          type: string
    user_options:
      properties:
        display_name:
          type: string
        email:
          type: string
        password:
          type: string
      required:
      - email
      - password
    kubeconfig_options:
      properties:
        duration:
          type: string
    invitation:
      properties:
        id:
          type: string
        name:
          type: string
        duration:
          type: string
        email:
          type: string
        organization_name:
          type: string
        organization_display_name:
          type: string
        role:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
        expires_at:
          type: string
          format: date-time
      required:
      - id
      - name
      - created_at
      - role
    invitation_options:
      properties:
        duration:
          type: string
        email:
          type: string
        role:
          type: string
      required:
      - email
      - role
