// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package types

import (
	"time"
)

// AnonymousAuthCondition Describes the condition under which anonymous auth
// should be enabled.
type AnonymousAuthCondition struct {
	// Path Path for which anonymous auth is enabled.
	Path *string `json:"path,omitempty"`
}

// AnonymousAuthConfig Provides the configuration for the anonymous authenticator.
type AnonymousAuthConfig struct {
	// Conditions If set, anonymous auth is only allowed if the request meets one of the
	// conditions.
	Conditions *[]AnonymousAuthCondition `json:"conditions,omitempty"`
	Enabled    *bool                     `json:"enabled,omitempty"`
}

// AuthenticationConfiguration provides versioned configuration for authentication.
type AuthenticationConfiguration struct {
	// Anonymous Provides the configuration for the anonymous authenticator.
	Anonymous *AnonymousAuthConfig `json:"anonymous,omitempty"`

	// Jwt A list of authenticator to authenticate Kubernetes users using
	// JWT compliant tokens. The authenticator will attempt to parse a raw ID token,
	// verify it's been signed by the configured issuer. The public key to verify the
	// signature is discovered from the issuer's public endpoint using OIDC discovery.
	// For an incoming token, each JWT authenticator will be attempted in
	// the order in which it is specified in this list.  Note however that
	// other authenticators may run before or after the JWT authenticators.
	// The specific position of JWT authenticators in relation to other
	// authenticators is neither defined nor stable across releases.  Since
	// each JWT authenticator must have a unique issuer URL, at most one
	// JWT authenticator will attempt to cryptographically validate the token.
	//
	// The minimum valid JWT payload must contain the following claims:
	// {
	//      "iss": "https://issuer.example.com",
	//      "aud": ["audience"],
	//      "exp": 1234567890,
	//      "<username claim>": "username"
	// }
	Jwt []JwtAuthenticator `json:"jwt"`
}

// ClaimMappings Provides the configuration for claim mapping
type ClaimMappings struct {
	// Extra Represents an option for the extra attribute.
	// expression must produce a string or string array value.
	// If the value is empty, the extra mapping will not be present.
	//
	// hard-coded extra key/value
	// - key: "foo"
	//   valueExpression: "'bar'"
	// This will result in an extra attribute - foo: ["bar"]
	//
	// hard-coded key, value copying claim value
	// - key: "foo"
	//   valueExpression: "claims.some_claim"
	// This will result in an extra attribute - foo: [value of some_claim]
	//
	// hard-coded key, value derived from claim value
	// - key: "admin"
	//   valueExpression: '(has(claims.is_admin) && claims.is_admin) ? "true":""'
	// This will result in:
	//  - if is_admin claim is present and true, extra attribute - admin: ["true"]
	//  - if is_admin claim is present and false or is_admin claim is not present, no extra attribute will be added
	Extra *[]ExtraMapping `json:"extra,omitempty"`

	// Groups Provides the configuration for a single prefixed claim or expression.
	Groups *PrefixedClaimOrExpression `json:"groups,omitempty"`

	// UID Provides the configuration for a single claim or expression.
	UID *ClaimOrExpression `json:"uid,omitempty"`

	// Username Provides the configuration for a single prefixed claim or expression.
	Username PrefixedClaimOrExpression `json:"username"`
}

// ClaimOrExpression Provides the configuration for a single claim or expression.
type ClaimOrExpression struct {
	// Claim The JWT claim to use.
	// Either claim or expression must be set.
	// Mutually exclusive with expression.
	Claim *string `json:"claim,omitempty"`

	// Expression Represents the expression which will be evaluated by CEL.
	//
	// CEL expressions have access to the contents of the token claims, organized into CEL variable:
	// - 'claims' is a map of claim names to claim values.
	//   For example, a variable named 'sub' can be accessed as 'claims.sub'.
	//   Nested claims can be accessed using dot notation, e.g. 'claims.foo.bar'.
	//
	// Documentation on CEL: https://kubernetes.io/docs/reference/using-api/cel/
	//
	// Mutually exclusive with claim.
	Expression *string `json:"expression,omitempty"`
}

// ClaimValidationRule Provides the configuration for a single claim validation rule.
type ClaimValidationRule struct {
	// Claim The name of a required claim.
	// Same as --oidc-required-claim flag.
	// Only string claim keys are supported.
	// Mutually exclusive with expression and message.
	Claim *string `json:"claim,omitempty"`

	// Expression Represents the expression which will be evaluated by CEL.
	// Must produce a boolean.
	//
	// CEL expressions have access to the contents of the token claims, organized into CEL variable:
	// - 'claims' is a map of claim names to claim values.
	//   For example, a variable named 'sub' can be accessed as 'claims.sub'.
	//   Nested claims can be accessed using dot notation, e.g. 'claims.foo.bar'.
	// Must return true for the validation to pass.
	//
	// Documentation on CEL: https://kubernetes.io/docs/reference/using-api/cel/
	//
	// Mutually exclusive with claim and requiredValue.
	Expression *string `json:"expression,omitempty"`

	// Message Customizes the returned error message when expression returns false.
	// message is a literal string.
	// Mutually exclusive with claim and requiredValue.
	Message *string `json:"message,omitempty"`

	// RequiredValue The value of a required claim.
	// Same as --oidc-required-claim flag.
	// Only string claim values are supported.
	// If claim is set and required_value is not set, the claim must be present with a value set to the empty string.
	// Mutually exclusive with expression and message.
	RequiredValue *string `json:"required_value,omitempty"`
}

// Cluster defines model for cluster.
type Cluster struct {
	AllocateInternalIP *bool   `json:"allocate_internal_ip,omitempty"`
	APIEndpoint        *string `json:"api_endpoint,omitempty"`

	// AuthenticationConfig provides versioned configuration for authentication.
	AuthenticationConfig     *AuthenticationConfiguration `json:"authentication_config,omitempty"`
	Condition                *string                      `json:"condition,omitempty"`
	CreatedAt                time.Time                    `json:"created_at"`
	DeletedAt                *time.Time                   `json:"deleted_at,omitempty"`
	DNSZones                 *[]string                    `json:"dns_zones,omitempty"`
	Duration                 *string                      `json:"duration,omitempty"`
	ExpiresAt                *time.Time                   `json:"expires_at,omitempty"`
	ID                       string                       `json:"id"`
	Name                     string                       `json:"name"`
	NoDefaultIngressProvider *bool                        `json:"no_default_ingress_provider,omitempty"`
	NoDefaultNetworkPlugin   *bool                        `json:"no_default_network_plugin,omitempty"`
	NodePoolsCount           *int                         `json:"node_pools_count,omitempty"`
	NodesCount               *int                         `json:"nodes_count,omitempty"`
	Organization             *string                      `json:"organization,omitempty"`
	PodSubnets               *[]string                    `json:"pod_subnets,omitempty"`
	ServiceSubnets           *[]string                    `json:"service_subnets,omitempty"`
	State                    *string                      `json:"state,omitempty"`
	UpdatedAt                *time.Time                   `json:"updated_at,omitempty"`
	Version                  *string                      `json:"version,omitempty"`
}

// ClusterAdvancedOptions Advanced options to apply to cluster, these may be specific to the backing cloud environment that is being used.
// Tread carefully.
type ClusterAdvancedOptions struct {
	// Kubevirt Options applied to kubevirt in case we're running in a kubevirt environment.
	Kubevirt *ClusterKubevirtOptions `json:"kubevirt,omitempty"`
}

// ClusterKubevirtOptions Options applied to kubevirt in case we're running in a kubevirt environment.
type ClusterKubevirtOptions struct {
	// Talos Options to apply to talos.
	Talos *ClusterTalosOptions `json:"talos,omitempty"`
}

// ClusterOptions defines model for cluster_options.
type ClusterOptions struct {
	// Advanced Advanced options to apply to cluster, these may be specific to the backing cloud environment that is being used.
	// Tread carefully.
	Advanced           *ClusterAdvancedOptions `json:"advanced,omitempty"`
	AllocateInternalIP *bool                   `json:"allocate_internal_ip,omitempty"`

	// AuthenticationConfig provides versioned configuration for authentication.
	AuthenticationConfig     *AuthenticationConfiguration `json:"authentication_config,omitempty"`
	ClusterTemplateName      *string                      `json:"cluster_template_name,omitempty"`
	Duration                 *string                      `json:"duration,omitempty"`
	IngressProvider          *string                      `json:"ingress_provider,omitempty"`
	Name                     string                       `json:"name"`
	NoClusterApps            *bool                        `json:"no_cluster_apps,omitempty"`
	NoDefaultIngressProvider *bool                        `json:"no_default_ingress_provider,omitempty"`
	NoDefaultNetworkPlugin   *bool                        `json:"no_default_network_plugin,omitempty"`
	NodePoolOptions          *[]NodePoolOptions           `json:"node_pool_options,omitempty"`
	PodSubnets               *[]string                    `json:"pod_subnets,omitempty"`
	ServiceSubnets           *[]string                    `json:"service_subnets,omitempty"`
	Version                  *string                      `json:"version,omitempty"`
}

// ClusterTalosOptions Options to apply to talos.
type ClusterTalosOptions struct {
	// AdditionalControlPlaneConfigPatches Patches applied to the talosconfig of controlplane nodes.
	AdditionalControlPlaneConfigPatches *[]map[string]interface{} `json:"additionalControlPlaneConfigPatches,omitempty"`

	// AdditionalSharedConfigPatches Patches applied to the talosconfig of all nodes.
	AdditionalSharedConfigPatches *[]map[string]interface{} `json:"additionalSharedConfigPatches,omitempty"`

	// AdditionalWorkerConfigPatches Patches applied to the talosconfig of worker nodes.
	AdditionalWorkerConfigPatches *[]map[string]interface{} `json:"additionalWorkerConfigPatches,omitempty"`
}

// ClusterTemplate defines model for cluster_template.
type ClusterTemplate struct {
	ClusterOptions ClusterOptions `json:"cluster_options"`
	IsDefault      bool           `json:"is_default"`
	Name           string         `json:"name"`
}

// Credential defines model for credential.
type Credential struct {
	CreatedAt              *time.Time         `json:"created_at,omitempty"`
	CredentialTemplateName *string            `json:"credential_template_name,omitempty"`
	Data                   *map[string][]byte `json:"data,omitempty"`
	DeletedAt              *time.Time         `json:"deleted_at,omitempty"`
	ID                     string             `json:"id"`
	Name                   string             `json:"name"`
	UpdatedAt              *time.Time         `json:"updated_at,omitempty"`
}

// CredentialOption defines model for credential_option.
type CredentialOption struct {
	Default     *string `json:"default,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
	Key         string  `json:"key"`
	Plaintext   *bool   `json:"plaintext,omitempty"`
	Type        *string `json:"type,omitempty"`
}

// CredentialOptions defines model for credential_options.
type CredentialOptions struct {
	CredentialTemplateName *string            `json:"credential_template_name,omitempty"`
	Data                   *map[string][]byte `json:"data,omitempty"`
	Name                   *string            `json:"name,omitempty"`
}

// CredentialTemplate defines model for credential_template.
type CredentialTemplate struct {
	Name    string              `json:"name"`
	Options *[]CredentialOption `json:"options,omitempty"`
}

// ExtraMapping Provides the configuration for a single extra mapping.
type ExtraMapping struct {
	// Key A string to use as the extra attribute key.
	// key must be a domain-prefix path (e.g. example.org/foo). All characters before the first "/" must be a valid
	// subdomain as defined by RFC 1123. All characters trailing the first "/" must
	// be valid HTTP Path characters as defined by RFC 3986.
	// key must be lowercase.
	// Required to be unique.
	Key string `json:"key"`

	// ValueExpression A CEL expression to extract extra attribute value.
	// valueExpression must produce a string or string array value.
	// "", [], and null values are treated as the extra mapping not being present.
	// Empty string values contained within a string array are filtered out.
	// CEL expressions have access to the contents of the token claims, organized into CEL variable:
	//
	// - 'claims' is a map of claim names to claim values.
	//   For example, a variable named 'sub' can be accessed as 'claims.sub'.
	//   Nested claims can be accessed using dot notation, e.g. 'claims.foo.bar'.
	//
	// Documentation on CEL: https://kubernetes.io/docs/reference/using-api/cel/
	ValueExpression string `json:"value_expression"`
}

// IdentityProvider defines model for identity_provider.
type IdentityProvider struct {
	DisplayName *string `json:"display_name,omitempty"`
	ID          string  `json:"id"`
	Name        string  `json:"name"`
}

// Invitation defines model for invitation.
type Invitation struct {
	CreatedAt               time.Time  `json:"created_at"`
	DeletedAt               *time.Time `json:"deleted_at,omitempty"`
	Duration                *string    `json:"duration,omitempty"`
	Email                   *string    `json:"email,omitempty"`
	ExpiresAt               *time.Time `json:"expires_at,omitempty"`
	ID                      string     `json:"id"`
	Name                    string     `json:"name"`
	OrganizationDisplayName *string    `json:"organization_display_name,omitempty"`
	OrganizationName        *string    `json:"organization_name,omitempty"`
	Role                    string     `json:"role"`
	UpdatedAt               *time.Time `json:"updated_at,omitempty"`
}

// InvitationOptions defines model for invitation_options.
type InvitationOptions struct {
	Duration *string `json:"duration,omitempty"`
	Email    string  `json:"email"`
	Role     string  `json:"role"`
}

// IPPool defines model for ip_pool.
type IPPool struct {
	Addresses *[]string `json:"addresses,omitempty"`
	ID        *string   `json:"id,omitempty"`
	Name      *string   `json:"name,omitempty"`
}

// Issuer Provides the configuration for an external provider's specific settings.
type Issuer struct {
	// AudienceMatchPolicy Defines how the "audiences" field is used to match the "aud" claim in the presented JWT.
	// Allowed values are:
	// 1. "MatchAny" when multiple audiences are specified and
	// 2. empty (or unset) or "MatchAny" when a single audience is specified.
	//
	// - MatchAny: the "aud" claim in the presented JWT must match at least one of the entries in the "audiences" field.
	// For example, if "audiences" is ["foo", "bar"], the "aud" claim in the presented JWT must contain either "foo" or "bar" (and may contain both).
	//
	// - "": The match policy can be empty (or unset) when a single audience is specified in the "audiences" field. The "aud" claim in the presented JWT must contain the single audience (and may contain others).
	//
	// For more nuanced audience validation, use claimValidationRules.
	//   example: claimValidationRule[].expression: 'sets.equivalent(claims.aud, ["bar", "foo", "baz"])' to require an exact match.
	AudienceMatchPolicy *string `json:"audience_match_policy,omitempty"`

	// Audiences The set of acceptable audiences the JWT must be issued to.
	// At least one of the entries must match the "aud" claim in presented JWTs.
	// Same value as the --oidc-client-id flag (though this field supports an array).
	// Required to be non-empty.
	Audiences []string `json:"audiences"`

	// CertificateAuthority Contains PEM-encoded certificate authority certificates
	// used to validate the connection when fetching discovery information.
	// If unset, the system verifier is used.
	// Same value as the content of the file referenced by the --oidc-ca-file flag.
	CertificateAuthority *string `json:"certificate_authority,omitempty"`

	// DiscoveryURL If specified, overrides the URL used to fetch discovery
	// information instead of using "{url}/.well-known/openid-configuration".
	// The exact value specified is used, so "/.well-known/openid-configuration"
	// must be included in discovery_url if needed.
	//
	// The "issuer" field in the fetched discovery information must match the "issuer.url" field
	// in the AuthenticationConfiguration and will be used to validate the "iss" claim in the presented JWT.
	// This is for scenarios where the well-known and jwks endpoints are hosted at a different
	// location than the issuer (such as locally in the cluster).
	//
	// Example:
	// A discovery url that is exposed using kubernetes service 'oidc' in namespace 'oidc-namespace'
	// and discovery information is available at '/.well-known/openid-configuration'.
	// discovery_url: "https://oidc.oidc-namespace/.well-known/openid-configuration"
	// certificateAuthority is used to verify the TLS connection and the hostname on the leaf certificate
	// must be set to 'oidc.oidc-namespace'.
	//
	// curl https://oidc.oidc-namespace/.well-known/openid-configuration (.discovery_url field)
	// {
	//     issuer: "https://oidc.example.com" (.url field)
	// }
	//
	// discovery_url must be different from url.
	// Required to be unique across all JWT authenticators.
	// Note that egress selection configuration is not used for this network connection.
	DiscoveryURL *string `json:"discovery_url,omitempty"`

	// EgressSelectorType An indicator of which egress selection should be used for sending all traffic related
	// to this issuer (discovery, JWKS, distributed claims, etc).  If unspecified, no custom dialer is used.
	// When specified, the valid choices are "controlplane" and "cluster".  These correspond to the associated
	// values in the --egress-selector-config-file.
	//
	// - controlplane: for traffic intended to go to the control plane.
	//
	// - cluster: for traffic intended to go to the system being managed by Kubernetes.
	EgressSelectorType *string `json:"egress_selector_type,omitempty"`

	// URL Points to the issuer URL in a format https://url or https://url/path.
	// This must match the "iss" claim in the presented JWT, and the issuer returned from discovery.
	// Same value as the --oidc-issuer-url flag.
	// Discovery information is fetched from "{url}/.well-known/openid-configuration" unless overridden by discovery_url.
	// Required to be unique across all JWT authenticators.
	// Note that egress selection configuration is not used for this network connection.
	URL string `json:"url"`
}

// JwtAuthenticator Provides the configuration for a single JWT authenticator.
type JwtAuthenticator struct {
	// ClaimMappings Provides the configuration for claim mapping
	ClaimMappings ClaimMappings `json:"claim_mappings"`

	// ClaimValidationRules Rules that are applied to validate token claims to authenticate users.
	ClaimValidationRules *[]ClaimValidationRule `json:"claim_validation_rules,omitempty"`

	// Issuer Provides the configuration for an external provider's specific settings.
	Issuer Issuer `json:"issuer"`

	// UserValidationRules Rules that are applied to final user before completing authentication.
	// These allow invariants to be applied to incoming identities such as preventing the
	// use of the system: prefix that is commonly used by Kubernetes components.
	// The validation rules are logically ANDed together and must all return true for the validation to pass.
	UserValidationRules *[]UserValidationRule `json:"user_validation_rules,omitempty"`
}

// KubeconfigOptions defines model for kubeconfig_options.
type KubeconfigOptions struct {
	Duration *string `json:"duration,omitempty"`
}

// LoginOptions defines model for login_options.
type LoginOptions struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Member defines model for member.
type Member struct {
	CreatedAt time.Time  `json:"created_at"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	Email     *string    `json:"email,omitempty"`
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Role      *string    `json:"role,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// Node defines model for node.
type Node struct {
	Condition  *string     `json:"condition,omitempty"`
	CreatedAt  time.Time   `json:"created_at"`
	DeletedAt  *time.Time  `json:"deleted_at,omitempty"`
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	ProviderID *string     `json:"provider_id,omitempty"`
	SystemInfo *SystemInfo `json:"system_info,omitempty"`
	UpdatedAt  *time.Time  `json:"updated_at,omitempty"`
}

// NodePool defines model for node_pool.
type NodePool struct {
	ClusterID                  *string            `json:"cluster_id,omitempty"`
	ControlPlane               *bool              `json:"control_plane,omitempty"`
	ControlPlaneComponentsOnly *bool              `json:"control_plane_components_only,omitempty"`
	CPUCount                   *int               `json:"cpu_count,omitempty"`
	CreatedAt                  time.Time          `json:"created_at"`
	DeletedAt                  *time.Time         `json:"deleted_at,omitempty"`
	DiskSize                   *string            `json:"disk_size,omitempty"`
	ID                         string             `json:"id"`
	LoadBalancer               *bool              `json:"load_balancer,omitempty"`
	Name                       string             `json:"name"`
	Nodes                      *[]Node            `json:"nodes,omitempty"`
	Quantity                   *int               `json:"quantity,omitempty"`
	RAMSize                    *string            `json:"ram_size,omitempty"`
	StorageResources           *[]StorageResource `json:"storage_resources,omitempty"`
	UpdatedAt                  *time.Time         `json:"updated_at,omitempty"`
}

// NodePoolOptions defines model for node_pool_options.
type NodePoolOptions struct {
	ControlPlane               *bool              `json:"control_plane,omitempty"`
	ControlPlaneComponentsOnly *bool              `json:"control_plane_components_only,omitempty"`
	CPUCount                   *int               `json:"cpu_count,omitempty"`
	DiskSize                   *string            `json:"disk_size,omitempty"`
	LoadBalancer               *bool              `json:"load_balancer,omitempty"`
	Name                       *string            `json:"name,omitempty"`
	Quantity                   *int               `json:"quantity,omitempty"`
	RAMSize                    *string            `json:"ram_size,omitempty"`
	StorageResources           *[]StorageResource `json:"storage_resources,omitempty"`
}

// Options defines model for options.
type Options struct {
	StorageResourceTypes *[]string `json:"storage_resource_types,omitempty"`
	Version              []string  `json:"version"`
}

// Organization defines model for organization.
type Organization struct {
	Condition               *string    `json:"condition,omitempty"`
	CreatedAt               time.Time  `json:"created_at"`
	CredentialReferenceName *string    `json:"credential_reference_name,omitempty"`
	DeletedAt               *time.Time `json:"deleted_at,omitempty"`
	DisplayName             *string    `json:"display_name,omitempty"`
	Duration                *string    `json:"duration,omitempty"`
	ExpiresAt               *time.Time `json:"expires_at,omitempty"`
	ID                      string     `json:"id"`
	Name                    string     `json:"name"`
	ProviderID              *string    `json:"provider_id,omitempty"`
	UpdatedAt               *time.Time `json:"updated_at,omitempty"`
	VoucherCode             *string    `json:"voucher_code,omitempty"`
}

// OrganizationOptions defines model for organization_options.
type OrganizationOptions struct {
	CredentialReferenceName *string `json:"credential_reference_name,omitempty"`
	DisplayName             *string `json:"display_name,omitempty"`
	Duration                *string `json:"duration,omitempty"`
	VoucherCode             *string `json:"voucher_code,omitempty"`
}

// PasswordOptions defines model for password_options.
type PasswordOptions struct {
	NewPassword string `json:"new_password"`
	OldPassword string `json:"old_password"`
}

// PasswordResetRequestOptions defines model for password_reset_request_options.
type PasswordResetRequestOptions struct {
	Email string `json:"email"`
}

// PrefixedClaimOrExpression Provides the configuration for a single prefixed claim or expression.
type PrefixedClaimOrExpression struct {
	// Claim The JWT claim to use.
	// Mutually exclusive with expression.
	Claim *string `json:"claim,omitempty"`

	// Expression Represents the expression which will be evaluated by CEL.
	//
	// CEL expressions have access to the contents of the token claims, organized into CEL variable:
	// - 'claims' is a map of claim names to claim values.
	//   For example, a variable named 'sub' can be accessed as 'claims.sub'.
	//   Nested claims can be accessed using dot notation, e.g. 'claims.foo.bar'.
	//
	// Documentation on CEL: https://kubernetes.io/docs/reference/using-api/cel/
	//
	// Mutually exclusive with claim and prefix.
	Expression *string `json:"expression,omitempty"`

	// Prefix This is prepended to claim's value to prevent clashes with existing names.
	// prefix needs to be set if claim is set and can be the empty string.
	// Mutually exclusive with expression.
	Prefix *string `json:"prefix,omitempty"`
}

// ResetPasswordOptions defines model for reset_password_options.
type ResetPasswordOptions struct {
	NewPassword string `json:"new_password"`
	ResetCode   string `json:"reset_code"`
}

// StorageResource defines model for storage_resource.
type StorageResource struct {
	Name     string  `json:"name"`
	Quantity string  `json:"quantity"`
	Type     *string `json:"type,omitempty"`
}

// SystemInfo defines model for system_info.
type SystemInfo struct {
	Architecture            *string `json:"architecture,omitempty"`
	BootID                  *string `json:"boot_id,omitempty"`
	ContainerRuntimeVersion *string `json:"container_runtime_version,omitempty"`
	KernelVersion           *string `json:"kernel_version,omitempty"`
	KubeletVersion          *string `json:"kubelet_version,omitempty"`
	MachineID               *string `json:"machine_id,omitempty"`
	OperatingSystem         *string `json:"operating_system,omitempty"`
	OsImage                 *string `json:"os_image,omitempty"`
	SystemUUID              *string `json:"system_uuid,omitempty"`
}

// Tokens defines model for tokens.
type Tokens struct {
	AccessToken  string `json:"AccessToken"`
	RefreshToken string `json:"RefreshToken"`
}

// UnprocessableEntityErrors defines model for unprocessable_entity_errors.
type UnprocessableEntityErrors struct {
	Errors []string `json:"errors"`
}

// User defines model for user.
type User struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	DisplayName *string    `json:"display_name,omitempty"`
	Email       string     `json:"email"`
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Password    *string    `json:"password,omitempty"`
	ProviderID  *string    `json:"provider_id,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
}

// UserOptions defines model for user_options.
type UserOptions struct {
	DisplayName *string `json:"display_name,omitempty"`
	Email       string  `json:"email"`
	Password    string  `json:"password"`
}

// UserValidationRule Provides the configuration for a single user info validation rule.
type UserValidationRule struct {
	// Expression Represents the expression which will be evaluated by CEL.
	// Must return true for the validation to pass.
	//
	// CEL expressions have access to the contents of UserInfo, organized into CEL variable:
	// - 'user' - authentication.k8s.io/v1, Kind=UserInfo object
	//    Refer to https://github.com/kubernetes/api/blob/release-1.28/authentication/v1/types.go#L105-L122 for the definition.
	//    API documentation: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#userinfo-v1-authentication-k8s-io
	//
	// Documentation on CEL: https://kubernetes.io/docs/reference/using-api/cel/
	Expression string `json:"expression"`

	// Message Customizes the returned error message when rule returns false.
	// message is a literal string.
	Message *string `json:"message,omitempty"`
}

// VerifyOptions defines model for verify_options.
type VerifyOptions struct {
	Code string `json:"code"`
	Type string `json:"type"`
}

// Workload defines model for workload.
type Workload struct {
	Condition            *string                 `json:"condition,omitempty"`
	CreatedAt            time.Time               `json:"created_at"`
	DeletedAt            *time.Time              `json:"deleted_at,omitempty"`
	ID                   string                  `json:"id"`
	Input                *map[string]interface{} `json:"input,omitempty"`
	Name                 string                  `json:"name"`
	Namespace            *string                 `json:"namespace,omitempty"`
	Provenience          *string                 `json:"provenience,omitempty"`
	UpdatedAt            *time.Time              `json:"updated_at,omitempty"`
	URLs                 *[]string               `json:"urls,omitempty"`
	WorkloadTemplateName *string                 `json:"workload_template_name,omitempty"`
}

// WorkloadOptions defines model for workload_options.
type WorkloadOptions struct {
	Input                *map[string]interface{} `json:"input,omitempty"`
	Name                 *string                 `json:"name,omitempty"`
	Namespace            *string                 `json:"namespace,omitempty"`
	WorkloadTemplateName *string                 `json:"workload_template_name,omitempty"`
}
